//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietphieunhaphang
    {
        public int chitietpnh_id { get; set; }
        public int phieunhaphang_id { get; set; }
        public int sanpham_id { get; set; }
        public int soluong { get; set; }
        public double dongia { get; set; }
        public double thanhtien { get; set; }
    
        public virtual phieunhaphang phieunhaphang { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
