//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khachhang()
        {
            this.giohangs = new HashSet<giohang>();
            this.hoadons = new HashSet<hoadon>();
        }
    
        public int khachhang_id { get; set; }
        public string khachhang_ten { get; set; }
        public System.DateTime khachhang_ngaysinh { get; set; }
        public string khachhang_sdt { get; set; }
        public string khachhang_diachi { get; set; }
        public string khachhang_email { get; set; }
        public string khachhang_matkhau { get; set; }
        public int trangthai_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giohang> giohangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadon> hoadons { get; set; }
        public virtual trangthai trangthai { get; set; }
    }
}
