//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangDienTu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class banhangdientuEntities : DbContext
    {
        public banhangdientuEntities()
            : base("name=banhangdientuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chitiethoadon> chitiethoadons { get; set; }
        public virtual DbSet<chitietphieunhaphang> chitietphieunhaphangs { get; set; }
        public virtual DbSet<chucvu> chucvus { get; set; }
        public virtual DbSet<giohang> giohangs { get; set; }
        public virtual DbSet<hoadon> hoadons { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<loaisanpham> loaisanphams { get; set; }
        public virtual DbSet<nhacungcap> nhacungcaps { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<phieugiaohang> phieugiaohangs { get; set; }
        public virtual DbSet<phieunhaphang> phieunhaphangs { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<trangthai> trangthais { get; set; }
        public virtual DbSet<trangthaihoadon> trangthaihoadons { get; set; }
    }
}
