//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhacungcap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhacungcap()
        {
            this.phieunhaphangs = new HashSet<phieunhaphang>();
        }
    
        public int ncc_id { get; set; }
        public string ncc_ten { get; set; }
        public string ncc_sdt { get; set; }
        public string ncc_email { get; set; }
        public string ncc_diachi { get; set; }
        public int trangthai_id { get; set; }
    
        public virtual trangthai trangthai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieunhaphang> phieunhaphangs { get; set; }
    }
}
