//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhanvien()
        {
            this.hoadons = new HashSet<hoadon>();
            this.phieunhaphangs = new HashSet<phieunhaphang>();
        }
    
        public int nhanvien_id { get; set; }
        public string nhanvien_ten { get; set; }
        public System.DateTime nhanvien_ngaysinh { get; set; }
        public string nhanvien_sdt { get; set; }
        public string nhanvien_email { get; set; }
        public string nhanvien_matkhau { get; set; }
        public int chucvu_id { get; set; }
        public int trangthai_id { get; set; }
    
        public virtual chucvu chucvu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadon> hoadons { get; set; }
        public virtual trangthai trangthai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieunhaphang> phieunhaphangs { get; set; }
    }
}
