//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieugiaohang
    {
        public int phieugiaohang_id { get; set; }
        public int hoadon_id { get; set; }
        public string phieugiaohang_tennguoinhan { get; set; }
        public int phieugiaohang_sdtnguoinhan { get; set; }
        public string phieugiaohang_diachinguoinhan { get; set; }
        public Nullable<System.DateTime> phieugiaohang_thoigiangiaohang { get; set; }
    
        public virtual hoadon hoadon { get; set; }
    }
}
